export enum OrderStatus {
  ORDERED = 'ORDERED',
  CONFIRMED_BY_RESTAURANT = 'CONFIRMED_BY_RESTAURANT',
  CANCELED_BY_CLIENT = 'CANCELED_BY_CLIENT',
  CANCELED_BY_RESTAURANT = 'CANCELED_BY_RESTAURANT',
  PAID = 'PAID'
}
